### ISSUE TITLE
Make image for Fusion360 worker

### ISSUE THREAD

**Issue by kaitlynhova** [machinabio/limbforge-service#6]
Include all dependancies and configs to start a new Fusion360 worker.

* moved from https://github.com/studioFATHOM/limbforge-service/issues/6

**Comment by luzlab** [comment]
Here's a quick rundown of the commands I ran to generate the image:
1. Create EC2 instance, 100GB provisioned storage, Win2016 Base AMI.
2. Log in and run as admin:
  1. command `winrm set winrm/config/Service/Auth @{Basic="true"}`
  2. command `winrm set winrm/config/Service @{AllowUnencrypted="true”}`
  3. powershell `Enable-PSRemoting -force`
  4. powershell `iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))`
  5. powershell `Set-Item wsman:\localhost\client\trustedhosts *`
  6. powershell `Restart-Service WinRM`
  7. powershell `winrm quickconfig` *interactive to open up firewall - find alternative!*
  8. powershell `wget https://dl.appstreaming.autodesk.com/production/installers/Fusion%20360%20Admin%20Install.exe -OutFile fusion360Installer.exe`
  9. powershell `.\fusion360Installer.exe --quiet`
  9. powershell `.\fusion360Installer.exe --update --quiet`
  10. powershell `choco install -y autodesk-fusion360` (instead of the preceeding 3 commands)
  11. powershell `choice install googlechrome`
4. Copied the plugin to the Fusion360 API plugins folder
3. Opened Fusion360
  1. Logged in with valid Autodesk credentials
  2. In API/Plugins, set "shift-io-agent" plugin to run at startup

**Comment by luzlab** [comment]
Done, ami-df3954bf is tested.
- Remote PS commands work
- Unable to RDP into the instances

**Comment by luzlab** [comment]
Check this documentation for using SysPrep to create image.
https://docs.aws.amazon.com/es_es/AWSEC2/latest/WindowsGuide/ec2launch.html#ec2launch-download

**Comment by luzlab** [comment]
I ran `C:\ProgramData\Amazon\EC2-Windows\Launch\Settings\EC2 Launch Settings.exe` on the Windows instance before shutting down and re-imaging. The app resets the initial boot behavior of the image. This allows us to use the resulting AMI to launch additional instances.

**Comment by luzlab** [comment]
New AMI is `ami-ce7815ae`.

**Comment by luzlab** [comment]
Tested logging in via RDP. Also successfully executed a remote command.

```
$pass = convertto-securestring "<PASSWORD>" -asplaintext -force
$cred = new-object -typename System.Management.Automation.PSCredential -argumentlist "Administrator",$pass
Invoke-Command -ComputerName 34.208.13.94 -Credential $cred -Authentication basic -scriptBlock {echo 0}
# returns `0`
```
